### PR TITLE
feat: use testcontainers-go module for qdrant

### PR DESCRIPTION
**Pull request by mdelapenya**
Hi :wave: from Testcontainers Go!

## What does this PR do?
It converts the current example living in examples/main.go to a Go test.

This test will leverage the recently released Testcontainers Go's module for QDrant (please see https://golang.testcontainers.org/modules/qdrant/)

Finally, I'm adding a minimal Github workflow to run tests on every merge commit and PR to master.

## Why is it important?
Dogfooding the module will improve it for anybody else.

### CODE REVIEW

**Review by Anush008 — CHANGES_REQUESTED** [review]
Hi @mdelapenya. Thanks for the contribution. It's looking great. I have one change request.

We'd want to specify the image version. Which will be bumped with each new Qdrant release.

Currently, it should be `v1.8.1`.

**Comment by Anush008** [comment]
Also, could you check `go mod tidy`?

**Comment by mdelapenya** [comment]
> Also, could you check `go mod tidy`? I am seeing some new changes.

✅ done in latest commits, thank you for your review 🙏

**Review by Anush008 — APPROVED** [review]
Thank you.

**Pull request merged**
